CREATE DATABASE IF NOT EXISTS airgradient;
USE airgradient;

CREATE TABLE IF NOT EXISTS measures (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    location_id INT NOT NULL,
    location_name VARCHAR(100),
    location_type VARCHAR(20),
    sensor_id VARCHAR(100),
    place_open BOOLEAN,
    recorded_at DATETIME NOT NULL,
    recorded_at_utc DATETIME NOT NULL,
    aggregated_records INT,
    pm25_raw FLOAT,
    pm25_corrected FLOAT,
    pm03_count FLOAT,
    co2_raw FLOAT,
    co2_corrected FLOAT,
    temp_raw FLOAT,
    temp_corrected FLOAT,
    heat_index_c FLOAT,
    humidity_raw FLOAT,
    humidity_corrected FLOAT,
    tvoc_ppb FLOAT,
    tvoc_index FLOAT,
    nox_index FLOAT,
    pm1 FLOAT,
    pm10 FLOAT,
    INDEX idx_utc (recorded_at_utc),
    INDEX idx_local (recorded_at),
    INDEX idx_sensor (sensor_id),
    UNIQUE KEY uq_sensor_time (sensor_id, recorded_at_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS outdoor_measures (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100),
    country VARCHAR(100),
    recorded_at_utc DATETIME NOT NULL,
    aqi_us INT,
    aqi_cn INT,
    main_pollutant VARCHAR(10),
    pm25_estimated FLOAT,
    temp_c FLOAT,
    humidity INT,
    pressure INT,
    wind_speed FLOAT,
    wind_direction INT,
    weather_icon VARCHAR(10),
    INDEX idx_outdoor_utc (recorded_at_utc),
    INDEX idx_outdoor_city (city, country),
    UNIQUE KEY uq_outdoor_city_time (city, country, recorded_at_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS weather (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    recorded_at_utc DATETIME NOT NULL,
    summary VARCHAR(100),
    icon VARCHAR(20),
    temperature FLOAT,
    apparent_temperature FLOAT,
    dew_point FLOAT,
    humidity FLOAT,
    pressure FLOAT,
    wind_speed FLOAT,
    wind_gust FLOAT,
    wind_bearing INT,
    cloud_cover FLOAT,
    uv_index FLOAT,
    visibility FLOAT,
    ozone FLOAT,
    precip_intensity FLOAT,
    precip_probability FLOAT,
    precip_type VARCHAR(20),
    INDEX idx_weather_utc (recorded_at_utc),
    UNIQUE KEY uq_weather_loc_time (lat, lon, recorded_at_utc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
